trigger:
  branches:
    include:
      - master
      - develop

variables:
  awsRegion: 'us-east-1'
  ecrRepository: 'devops-service'
  imageTag: '$(Build.BuildId)'
  serviceName: 'devops-service'

stages:
  - stage: Build
    displayName: Build and Test
    jobs:
      - job: Build
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: UseDotNet@2
            inputs:
              packageType: 'sdk'
              version: '8.0.x'
          
          - script: |
              ls

          - script: |
              cd src/DevOpsService
              dotnet restore
              dotnet build -c Release
              cd ../../tests/DevOpsService.Tests
              dotnet test --no-build --verbosity normal
              cd ../../
            displayName: 'Restore Build Test'

          - task: SonarCloudPrepare@1
            inputs:
              SonarCloud: 'SonarOnline'
              organization: 'azure-pedrinchi'
              scannerMode: 'MSBuild'
              projectKey: 'devops-service'

          - script: |
              dotnet tool install --global dotnet-sonarscanner
              export PATH="$PATH:/root/.dotnet/tools"
              dotnet sonarscanner begin /k:"devops-service" /o:"azure-pedrinchi" /d:sonar.scanner.skipJreProvisioning=true /d:sonar.sources="src/DevOpsService" /d:sonar.cs.vscoveragexml.reportsPaths="coverage.xml"
              dotnet build
              dotnet sonarscanner end
            displayName: 'Run SonarCloud Analysis'

